/* Datos del prototipo de diseño, tal como vinieron. Los tipos de acá son los del
   prototipo (legacy) y NO son el contrato: `fixtures.ts` los mapea al contrato real.
   Cuando exista la API de NexoPOS este archivo se borra entero. */

interface Product {
  id: string; name: string; brand: string; pasilloId: string; subCategory: string;
  price: number; originalPrice?: number; discountPercentage?: number; unit: string;
  imageUrl: string; extraImages?: string[]; type: 'canonico' | 'propio'; ean?: string; stock: number;
  dailyQuota?: number; quotaRemaining?: number; isOffer?: boolean; packTag?: string;
  storeId: string; storeName: string; description?: string;
}
interface Pasillo {
  id: string; name: string; iconName: string; imageUrl: string;
  subCategories: string[]; productCount: number; isPopular?: boolean;
}
interface Store {
  id: string; name: string; category: string; address: string; town: string;
  verified: boolean; phone: string; openingHours: string; hasDelivery: boolean;
  hasTakeaway: boolean; allowsCredit: boolean; logoUrl?: string;
}

export const PASILLOS: Pasillo[] = [
  {
    id: 'ofertas',
    name: 'Ofertas imperdibles',
    iconName: 'Percent',
    imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=300&q=80',
    subCategories: ['Semana Saludable', 'Packs Ahorro x24', 'Descuentos del Día', '2x1 en Bebidas'],
    productCount: 24,
    isPopular: true,
  },
  {
    id: 'despensa',
    name: 'Despensa',
    iconName: 'Package',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=300&q=80',
    subCategories: ['Aceites y Aderezos', 'Arroz y Legumbres', 'Fideos y Pastas', 'Galletitas y Snacks', 'Café, Té y Yerba'],
    productCount: 142,
    isPopular: true,
  },
  {
    id: 'bebidas-alcoholicas',
    name: 'Bebidas alcohólicas',
    iconName: 'Wine',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=300&q=80',
    subCategories: ['Cervezas en Lata y Botella', 'Aperitivos y Amargos (Campari, Fernet)', 'Vinos Tintos y Blancos', 'Espumantes y Licores'],
    productCount: 88,
    isPopular: true,
  },
  {
    id: 'higiene-belleza',
    name: 'Higiene personal y belleza',
    iconName: 'Sparkles',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&q=80',
    subCategories: ['Shampoo y Acondicionador', 'Jabones y Cremas', 'Cuidado Dental', 'Desodorantes'],
    productCount: 65,
    isPopular: true,
  },
  {
    id: 'limpieza-hogar',
    name: 'Limpieza del hogar',
    iconName: 'SprayCan',
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=300&q=80',
    subCategories: ['Lavado de Ropa (Skip, Ace)', 'Desinfectantes y Lavandinas', 'Rollos de Cocina y Papel', 'Limpiadores de Pisos'],
    productCount: 74,
    isPopular: true,
  },
  {
    id: 'agua-jugos-gaseosas',
    name: 'Agua, jugos y gaseosas',
    iconName: 'GlassWater',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=300&q=80',
    subCategories: ['Gaseosas Cola y Sabores', 'Aguas Minerales y Saborizadas', 'Jugos Listos y Concentrados', 'Isotónicas y Energizantes'],
    productCount: 52,
    isPopular: true,
  },
  {
    id: 'lacteos',
    name: 'Lácteos y Quesos',
    iconName: 'Milk',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&q=80',
    subCategories: ['Leches Enteras y Descremadas', 'Yogures y Postres', 'Quesos de Barra y Untables', 'Mantecas y Cremas'],
    productCount: 46,
    isPopular: true,
  },
  {
    id: 'frescos-propios',
    name: 'Elaboración Propia & Rotisería',
    iconName: 'Utensils',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=300&q=80',
    subCategories: ['Prepizzas a la Piedra', 'Pan Criollo y Casero', 'Milanesas Caseras', 'Empanadas del Día'],
    productCount: 18,
    isPopular: true,
  },
  {
    id: 'bebes',
    name: 'Bebés y Maternidad',
    iconName: 'Baby',
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=300&q=80',
    subCategories: ['Pañales y Toallitas', 'Alimentación Infantil', 'Higiene del Bebé'],
    productCount: 30,
    isPopular: false,
  },
  {
    id: 'farmacia',
    name: 'Farmacia y Primeros Auxilios',
    iconName: 'Cross',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&q=80',
    subCategories: ['Analgésicos de Venta Libre', 'Alcohol y Gasas', 'Vitaminas y Suplementos'],
    productCount: 22,
    isPopular: false,
  }
];

export const STORES_MORRISON: Store[] = [
  {
    id: 'store-supersol',
    name: 'Súper SOL',
    category: 'Supermercado & Carnicería',
    address: 'Av. San Martín 342, Morrison',
    town: 'Morrison',
    verified: true,
    phone: '03537 46-2180',
    openingHours: 'Lun a Sáb 08:30 a 13:00 y 17:00 a 21:30 | Dom 09:00 a 13:00',
    hasDelivery: true,
    hasTakeaway: true,
    allowsCredit: true,
    logoUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=100&q=80',
  },
  {
    id: 'store-sancayetano',
    name: 'Almacén San Cayetano',
    category: 'Almacén y Fiambrería',
    address: 'Calle Chacabuco 180, Morrison',
    town: 'Morrison',
    verified: true,
    phone: '03537 46-1122',
    openingHours: 'Lun a Sáb 08:00 a 13:00 y 17:30 a 21:30',
    hasDelivery: true,
    hasTakeaway: true,
    allowsCredit: true,
    logoUrl: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=100&q=80',
  },
  {
    id: 'store-ferreteria',
    name: 'Ferretería El Puente',
    category: 'Ferretería y Corralón',
    address: 'Bv. Belgrano 510, Morrison',
    town: 'Morrison',
    verified: true,
    phone: '03537 46-3401',
    openingHours: 'Lun a Vie 08:00 a 12:30 y 15:30 a 20:00 | Sáb 08:00 a 13:00',
    hasDelivery: true,
    hasTakeaway: true,
    allowsCredit: true,
    logoUrl: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=100&q=80',
  },
  {
    id: 'store-donarosa',
    name: 'Rotisería Doña Rosa',
    category: 'Comidas Caseras y Empanadas',
    address: 'Calle Córdoba 215, Morrison',
    town: 'Morrison',
    verified: true,
    phone: '03537 46-5590',
    openingHours: 'Mar a Dom 11:30 a 14:00 y 20:00 a 23:30',
    hasDelivery: true,
    hasTakeaway: true,
    allowsCredit: false,
    logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=100&q=80',
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-stella-x24',
    name: 'Cerveza Rubia Stella Artois Pack x24 Latas 473cc',
    brand: 'Stella Artois',
    pasilloId: 'bebidas-alcoholicas',
    subCategory: 'Cervezas en Lata y Botella',
    price: 36900,
    originalPrice: 45000,
    discountPercentage: 18,
    unit: 'Pack 24 un.',
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=600&q=80',
    extraImages: [
      'https://images.unsplash.com/photo-1571613316887-6f8d5cbf7ef7?w=600&q=80',
      'https://images.unsplash.com/photo-1618183479302-1e0aa382c36b?w=600&q=80',
      'https://images.unsplash.com/photo-1595475207225-428b62bda831?w=600&q=80',
    ],
    type: 'canonico',
    ean: '7790895000452',
    stock: 35,
    isOffer: true,
    packTag: 'x24 473cc',
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Catálogo Maestro B2B. Cerveza lager premium dorada y equilibrada, elaborada con lúpulo Saaz.'
  },
  {
    id: 'prod-nescafe-gold',
    name: 'Café Instantáneo Nescafé Gold Frasco 100g',
    brand: 'Nescafé',
    pasilloId: 'despensa',
    subCategory: 'Café, Té y Yerba',
    price: 7450,
    originalPrice: 9200,
    discountPercentage: 19,
    unit: '100g',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&q=80',
    extraImages: ['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600&q=80'],
    type: 'canonico',
    ean: '7613035334190',
    stock: 28,
    isOffer: true,
    packTag: 'Formato Recarga',
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Café tostado soluble 100% puro con granos de café arábica finamente molidos.'
  },
  {
    id: 'prod-skip-3l',
    name: 'Jabón Líquido Skip Concentrado Doypack 3L',
    brand: 'Skip',
    pasilloId: 'limpieza-hogar',
    subCategory: 'Lavado de Ropa (Skip, Ace)',
    price: 12800,
    originalPrice: 16000,
    discountPercentage: 20,
    unit: '3 Litros',
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&q=80',
    type: 'canonico',
    ean: '7791290008432',
    stock: 19,
    isOffer: true,
    packTag: 'Hasta 20% Ahorro',
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Tecnología Bio-enzimas con fragancia duradera. Rinde hasta 30 lavados en máquina automática.'
  },
  {
    id: 'prod-stella-x6',
    name: 'Cerveza Stella Artois Sin Alcohol 6 Latas 473cc',
    brand: 'Stella Artois',
    pasilloId: 'bebidas-alcoholicas',
    subCategory: 'Cervezas en Lata y Botella',
    price: 9800,
    originalPrice: 11900,
    discountPercentage: 17,
    unit: 'Pack 6 un.',
    imageUrl: 'https://images.unsplash.com/photo-1584225064785-c62a8b43d148?w=600&q=80',
    type: 'canonico',
    ean: '7790895066782',
    stock: 42,
    isOffer: true,
    packTag: '6 Latas 473cc',
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Elaborada sin alcohol pero manteniendo el sabor original y carácter equilibrado.'
  },
  {
    id: 'prod-integra-barras',
    name: 'Barra Proteica Íntegra Maní y Chocolate Pack x12',
    brand: 'Íntegra',
    pasilloId: 'despensa',
    subCategory: 'Galletitas y Snacks',
    price: 8600,
    originalPrice: 10500,
    discountPercentage: 18,
    unit: 'Pack 12 un.',
    imageUrl: 'https://images.unsplash.com/photo-1622484216802-094191d830b5?w=600&q=80',
    type: 'canonico',
    ean: '7798319200115',
    stock: 15,
    isOffer: true,
    packTag: '15g Proteína',
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Snack saludable con alto aporte de fibra y 15g de proteína por porción. Sin TACC.'
  },
  {
    id: 'prod-leche-laserenisima',
    name: 'Leche Larga Vida La Serenísima UAT 1L (Pack x6)',
    brand: 'La Serenísima',
    pasilloId: 'lacteos',
    subCategory: 'Leches Enteras y Descremadas',
    price: 9600,
    originalPrice: 11400,
    discountPercentage: 15,
    unit: 'Pack 6 litros',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&q=80',
    type: 'canonico',
    ean: '7793940001021',
    stock: 50,
    isOffer: true,
    packTag: 'Pack Familiar',
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Leche entera pasteurizada enriquecida con vitaminas A y D.'
  },
  {
    id: 'prod-campari',
    name: 'Aperitivo Campari Bitter Botella 750ml',
    brand: 'Campari',
    pasilloId: 'bebidas-alcoholicas',
    subCategory: 'Aperitivos y Amargos (Campari, Fernet)',
    price: 8900,
    originalPrice: 10200,
    discountPercentage: 12,
    unit: '750ml',
    imageUrl: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?w=600&q=80',
    type: 'canonico',
    ean: '7790950000188',
    stock: 22,
    isOffer: false,
    packTag: 'Original Italia',
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Aperitivo italiano de infusión aromática con hierbas y frutas.'
  },
  {
    id: 'prod-fernet-branca',
    name: 'Fernet Branca 750ml',
    brand: 'Branca',
    pasilloId: 'bebidas-alcoholicas',
    subCategory: 'Aperitivos y Amargos (Campari, Fernet)',
    price: 13500,
    unit: '750ml',
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&q=80',
    type: 'canonico',
    ean: '7790412000012',
    stock: 40,
    isOffer: false,
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'El clásico de las juntadas con amigos. Añejado en cubas de roble de Eslavonia.'
  },
  {
    id: 'prod-prepizzas-sol',
    name: 'Prepizzas Caseras a la Piedra de Cebolla y Muzzarella (x2)',
    brand: 'Elaboración Súper SOL',
    pasilloId: 'frescos-propios',
    subCategory: 'Prepizzas a la Piedra',
    price: 4200,
    unit: 'Pack 2 unidades',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80',
    type: 'propio', // D1: Producto propio del comercio
    stock: 8,
    dailyQuota: 20, // D4: Cupo del día
    quotaRemaining: 8,
    isOffer: false,
    packTag: 'Horneadas Hoy',
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Masa madre fermentada 24hs en la panadería de Súper SOL con salsa casera y orégano de huerta.'
  },
  {
    id: 'prod-pan-criollo',
    name: 'Pan Criollo con Grasa Tradicional x 1 Kg',
    brand: 'Panadería Súper SOL',
    pasilloId: 'frescos-propios',
    subCategory: 'Pan Criollo y Casero',
    price: 2800,
    unit: '1 kg',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80',
    type: 'propio',
    stock: 12,
    dailyQuota: 30,
    quotaRemaining: 12,
    isOffer: false,
    packTag: 'Recién Salido',
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Elaborado todas las mañanas en el horno del súper. Hojaldrado tradicional cordobés.'
  },
  {
    id: 'prod-aceite-natura',
    name: 'Aceite de Girasol Natura Botella 1.5L',
    brand: 'Natura',
    pasilloId: 'despensa',
    subCategory: 'Aceites y Aderezos',
    price: 3150,
    unit: '1.5 Litros',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80',
    type: 'canonico',
    ean: '7790272001019',
    stock: 64,
    isOffer: false,
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Aceite puro de girasol libre de gluten. Vitamina E natural.'
  },
  {
    id: 'prod-yerba-playadito',
    name: 'Yerba Mate Playadito Tradicional 1kg',
    brand: 'Playadito',
    pasilloId: 'despensa',
    subCategory: 'Café, Té y Yerba',
    price: 4600,
    originalPrice: 5300,
    discountPercentage: 13,
    unit: '1 Kg',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&q=80',
    type: 'canonico',
    ean: '7790387011032',
    stock: 45,
    isOffer: true,
    packTag: 'Con Palo',
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Estacionamiento natural de 12 a 18 meses. Suave y rendidora para el mate diario.'
  },
  {
    id: 'prod-shampoo-dove',
    name: 'Shampoo Dove Reconstrucción Completa 400ml',
    brand: 'Dove',
    pasilloId: 'higiene-belleza',
    subCategory: 'Shampoo y Acondicionador',
    price: 4950,
    unit: '400 ml',
    imageUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&q=80',
    type: 'canonico',
    ean: '7791293021941',
    stock: 22,
    isOffer: false,
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'Con activos reparadores Nutri-Keratin para nutrir profundamente el cabello dañado.'
  },
  {
    id: 'prod-coca-cola-225',
    name: 'Gaseosa Coca-Cola Sabor Original Botella 2.25L',
    brand: 'Coca-Cola',
    pasilloId: 'agua-jugos-gaseosas',
    subCategory: 'Gaseosas Cola y Sabores',
    price: 3400,
    unit: '2.25 Litros',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&q=80',
    type: 'canonico',
    ean: '7790895000998',
    stock: 80,
    isOffer: false,
    packTag: 'Retornable / Descartable',
    storeId: 'store-supersol',
    storeName: 'Súper SOL',
    description: 'El sabor refrescante inconfundible de siempre para compartir en la mesa familiar.'
  }
];
